### ISSUE TITLE
Inertial data

### ISSUE THREAD

**Issue by moshanATucsd** [feixh/VISMA#1]
Hi, 

Thanks for sharing this! Since this is a VIO dataset, I am wondering whether we could obtain IMU data in python? Could you kindly provide an example?

**Comment by feixh** [comment]
> Hi,
> 
> Thanks for sharing this! Since this is a VIO dataset, I am wondering whether we could obtain IMU data in python? Could you kindly provide an example?

To access the IMU data, you need to use the raw data in the format of rosbags. You familiar with ROS? I can come up with a python script to convert rosbags to txt files later on. But there is no guarantee, please let me whether you can manage to use ROS.

**Comment by moshanATucsd** [comment]
I see, I can use ROS bag to get that, thanks!
