### ISSUE TITLE
Are depth map streams provided in the VISMA dataset?

### ISSUE THREAD

**Issue by JiamingSuen** [feixh/VISMA#3]
Hello Dr. Xiaohan Fei, thanks for this great work.
I wonder if the depth map streams are provided in this dataset? I checked the given rosbags, and found no depth map topic inside them. Is it possible for you to add the raw depth streams to the dataset if they are still available? This would help a lot in my ongoing project and this line of research as well.
Thanks for your time!

**Comment by feixh** [comment]
Hi Jiaming, for VISMA dataset, we didn't have a synchronized depth stream recorded. But we used a separate Kinect sensor to scan the scene and have a dense reconstruction from the Kinect data. Not sure whether the reconstruction is useful to you at all, but if you have the alignment of the dense reconstruction and your VIO, you can project the point cloud to the RGB frames recorded in the rosbags and have some sort of pseudo ground truth for depth. This is what we did for our ICRA paper on depth prediction. Hope this helps.

**Comment by JiamingSuen** [comment]
Thanks a lot for your reply! I'll try it out later.
